# inspired by https://github.com/mjstealey/wordpress-nginx-docker
version: '3.6'
services:

  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-php8.1-fpm-alpine}
    env_file:
      - ./.env
      - ./.env.docker
    container_name: wordpress
    volumes:
      # read our php conf last (to circumvent https://github.com/docker-library/wordpress/blob/b5d8e4f40bef55630fcf52a0f2830619f4df140e/latest/php7.4/fpm/Dockerfile#L76)
      - ${PHP_CONF_FILE:-./.docker/php/conf.ini}:/usr/local/etc/php/conf.d/zzz_conf.ini
      - ${WEBROOT_DIR:-.}:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
      - WORDPRESS_TABLE_PREFIX=${WP_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-password}
    entrypoint: [] # set to empty array to override https://github.com/docker-library/wordpress/blob/master/docker-entrypoint.sh (which copies wordpress installation to webroot)
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    env_file:
      - ./.env
      - ./.env.docker
    container_name: mysql
    volumes:
      - ${MYSQL_DATA_DIR:-./.docker/mysql}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_NAME:-wordpress}
    restart: always

  nginx:
    image: nginx:${NGINX_VERSION:-alpine}
    env_file:
      - ./.env.docker
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_CONF_FILE:-./.docker/nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOG_DIR:-./.docker/nginx/logs}:/var/log/nginx
      - ${SSL_CERTS_DIR:-./.docker/ssl}:/ssl
      - ${WEBROOT_DIR:-.}:/var/www/html
    depends_on:
      - wordpress
    restart: always

  wpcli:
    image: wordpress:${WPCLI_VERSION:-cli-php7.4}
    env_file:
      - ./.env.docker
    container_name: wpcli
    depends_on:
      - mysql
      - wordpress
    links:
      - mysql
    entrypoint: wp
    command: "--info"
    volumes:
      - ${WEBROOT_DIR:-.}:/var/www/html

  adminer:
    image: adminer
    container_name: adminer
    links:
      - mysql
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 8080:8080
    restart: always
